version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=wackcap
    healthcheck:
          test: "exit 0"
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build: ./src
    volumes:
      - ./src/:/var/www/app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - db
      - redis